version: "3.8"

services:
  registry:
    image: registry:2
    ports:
      - target: 5000
        published: 80

  serverdb:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: notaryserver
      MYSQL_USER: server
      MYSQL_PASSWORD: server
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  signerdb:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: notarysigner
      MYSQL_USER: signer
      MYSQL_PASSWORD: signer
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  notaryserver:
    image: notary:server-0.6.1-2
    environment:
      NOTARY_SERVER_STORAGE_DB_URL: &serverdb_dsn server:server@tcp(serverdb:3306)/notaryserver?parseTime=true
      NOTARY_SERVER_LOGGING_LEVEL: debug
      NOTARY_SERVER_TRUST_SERVICE_TYPE: local
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - target: 4443
        published: 443
    command:
      - -config=/notary/server/server-config.json
    volumes:
      - ./certs/server:/certs:z

  notarysigner:
    image: notary:signer-0.6.1-2
    environment:
      NOTARY_SIGNER_STORAGE_DB_URL: &signerdb_dsn signer:signer@tcp(signerdb:3306)/notarysigner?parseTime=true
      NOTARY_SIGNER_STORAGE_DEFAULT_ALIAS: passwordalias2021
      NOTARY_SIGNER_PASSWORDALIAS2021: testpassword
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    command:
      - -config=/notary/signer/signer-config.json
    volumes:
      - ./certs/signer:/certs:z

  migrations:
    image: migrate/migrate
    entrypoint: ["/bin/sh", "-c"]
    environment:
      SERVERDB_DSN: *serverdb_dsn
      SIGNERDB_DSN: *signerdb_dsn
    command:
    - |
      set -eux

      apk add git
      git clone https://github.com/theupdateframework/notary.git
      cd notary
      git checkout v0.6.1

      until migrate -path=migrations/server/mysql -database=mysql://$${SERVERDB_DSN} up; do
        sleep 1
      done

      until migrate -path=migrations/signer/mysql -database=mysql://$${SIGNERDB_DSN} up; do
        sleep 1
      done
