apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notaryserver-tls
spec:
  secretName: notaryserver-tls
  dnsNames:
  - localhost
  - notaryserver
  - notaryserver.localhost
  issuerRef:
    name: notary-ca
    kind: Issuer