apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-tls
spec:
  secretName: postgres-tls
  commonName: postgres
  dnsNames:
  - notary-postgresql
  issuerRef:
    kind: Issuer
    name: notary-ca
