apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
spec:
  secretName: registry-tls
  dnsNames:
  - notary.localhost
  - registry.localhost
  - localhost
  issuerRef:
    name: notary-ca
    kind: Issuer