version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /etc/docker/tls/tls.crt
    key: /etc/docker/tls/tls.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3