apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart: traefik
  version: 9.12.3
  targetNamespace: traefik-system
  repo: https://helm.traefik.io/traefik
  valuesContent: |-
    globalArguments:
      - --global.checknewversion
    additionalArguments:
      - --accesslog
      - --accesslog.format=json
      # always redirect from http to https
      # do not use "websecure" here because it will not point to 443 but to 8443
      - --entrypoints.web.http.redirections.entrypoint.to=:443
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
