apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: docker-swarm-node-2
  name: docker-swarm-node-2
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: docker-swarm-node-2
    spec:
      domain:
        devices:
          disks:
          - name: root-disk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
      volumes:
      - name: root-disk
        dataVolume:
          name: root-disk-2
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: userdata-cloud-init
          networkDataSecretRef:
            name: networkdata-cloud-init

  dataVolumeTemplates:
  - metadata:
      name: root-disk-2
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
      source:
        http:
          # url: https://cloud.debian.org/images/cloud/buster/20201214-484/debian-10-nocloud-amd64-20201214-484.qcow2
          url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2

---

apiVersion: v1
kind: Service
metadata:
  name: docker-swarm-node-2
spec:
  selector:
    kubevirt.io/vm: docker-swarm-node-2
  type: LoadBalancer
  loadBalancerIP: 145.100.106.210
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443