apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notary

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
  - name: notaryserver
    literals:
      - |
        server-config.json=
        {
          "server": {
                  "http_addr": ":4443"
          },
          "trust_service": {
                  "type": "local"
          },
          "logging": {
                  "level": "info"
          },
          "storage": {
                  "backend": "memory"
          }
        }