apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notary
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - http:
        paths:
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 5000

          - path: /v2/{repository:[a-z0-9/]+(?:[._-][a-z0-9/]+)*}/_trust
            pathType: Prefix
            backend:
              service:
                name: notaryserver
                port:
                  number: 4443
  tls:
    - secretName: registry-tls