apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notary

resources:
- deployment.yaml
- service.yaml
- ingressroute.yaml
- serverstransport.yaml

configMapGenerator:
  - name: registry-config
    files:
      - config/config.yml