apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notaryserver-tls
spec:
  secretName: notaryserver-tls
  dnsNames:
  - notary.localhost
  issuerRef:
    name: notary-ca
    kind: Issuer