apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart: traefik
  version: 9.12.3
  targetNamespace: traefik-system
  repo: https://helm.traefik.io/traefik
