apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary
spec:
  selector:
    matchLabels:
      app: notary
  template:
    metadata:
      labels:
        app: notary
    spec:
      containers:
      - name: server
        image: notary:server-0.6.1-2
        args:
          - -config=/etc/notary/config/server-config.json
        envFrom:
          - secretRef:
              name: notaryserver
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4443
          name: http
        volumeMounts:
          - mountPath: /etc/notary/config
            name: notaryserver-config
          - mountPath: /etc/notary/tls
            name: notaryserver-tls
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
      - name: signer
        image: notary:signer-0.6.1-2
        args:
          - -config=/etc/notary/config/signer-config.json
        envFrom:
          - secretRef:
              name: notarysigner
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7899
          name: grpc
        volumeMounts:
          - mountPath: /etc/notary/config
            name: notarysigner-config
          - mountPath: /etc/notary/tls
            name: notarysigner-tls
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
      volumes:
        - name: notaryserver-config
          configMap:
            name: notaryserver
            optional: false
        - name: notaryserver-tls
          secret:
            secretName: notaryserver-tls
            optional: false
        - name: notarysigner-config
          configMap:
            name: notarysigner
            optional: false
        - name: notarysigner-tls
          secret:
            secretName: notarysigner-tls
            optional: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
