apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary
spec:
  selector:
    matchLabels:
      app: notary
  template:
    metadata:
      labels:
        app: notary
    spec:
      initContainers:
      - image: busybox
        name: file-permissions-fixer
        command:
        - /bin/sh
        - -cx
        - |
          cp -v /certs/raw/server/* /certs/memory/server/
          cp -v /certs/raw/signer/* /certs/memory/signer/
          chown 1000:1000 /certs/memory/server/* /certs/memory/signer/*
          chmod 600 /certs/memory/server/* /certs/memory/signer/*

        volumeMounts:
          - mountPath: /certs/memory/server
            name: owned-server-tls
          - mountPath: /certs/memory/signer
            name: owned-signer-tls
          - mountPath: /certs/raw/server
            name: notaryserver-tls
          - mountPath: /certs/raw/signer
            name: notarysigner-tls

      containers:
      - name: server
        image: notary:server-0.6.1-2
        args:
          - -config=/etc/notary/config/server-config.json
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4443
          name: http
        volumeMounts:
          - mountPath: /etc/notary/config
            name: notaryserver-config
          - mountPath: /etc/notary/tls
            name: owned-server-tls
        livenessProbe:
          httpGet:
            path: /v2/
            port: 4443
            scheme: HTTPS
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true

      - name: signer
        image: notary:signer-0.6.1-2
        args:
          - -config=/etc/notary/config/signer-config.json
        envFrom:
          - secretRef:
              name: notarysigner
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7899
          name: grpc
        volumeMounts:
          - mountPath: /etc/notary/config
            name: notarysigner-config
          - mountPath: /etc/notary/tls
            name: owned-signer-tls
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true

      volumes:
        - name: notaryserver-config
          configMap:
            name: notaryserver
            optional: false
        - name: notaryserver-tls
          secret:
            secretName: notaryserver-tls
            optional: false
        - name: notarysigner-config
          configMap:
            name: notarysigner
            optional: false
        - name: notarysigner-tls
          secret:
            secretName: notarysigner-tls
            optional: false
        - name: owned-server-tls
          emptyDir:
            medium: Memory
        - name: owned-signer-tls
          emptyDir:
            medium: Memory

      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
