apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notary

resources:
- deployment.yaml
- service.yaml
- migrate-job.yaml
- ingressroute.yaml
- serverstransport.yaml

secretGenerator:
  - name: notaryserver
    literals:
    - NOTARY_SERVER_STORAGE_DB_URL=server:server@tcp(mariadb.mariadb:3306)/notaryserver?parseTime=True
  - name: notarysigner
    literals:
    - NOTARY_SIGNER_STORAGE_DB_URL=signer:signer@tcp(mariadb.mariadb:3306)/notarysigner?parseTime=True
    - NOTARY_SIGNER_NOTARYDEMOPASSWORD=demopassword

configMapGenerator:
  - name: scripts
    files:
    - scripts/migrate.sh

  - name: notaryserver
    literals:
      - |
        server-config.json=
        {
                "server": {
                        "http_addr": ":4443",
                        "tls_key_file": "/etc/notary/tls/tls.key",
                        "tls_cert_file": "/etc/notary/tls/tls.crt"
                },
                "trust_service": {
                        "type": "remote",
                        "hostname": "localhost",
                        "port": "7899",
                        "key_algorithm": "ecdsa",
                        "tls_ca_file": "/etc/notary/tls/ca.crt",
                        "tls_client_cert": "/etc/notary/tls/tls.crt",
                        "tls_client_key": "/etc/notary/tls/tls.key"
                },
                "logging": {
                        "level": "info"
                },
                "storage": {
                        "backend": "mysql"
                }
        }

  - name: notarysigner
    literals:
      - |
        signer-config.json=
        {
                "server": {
                        "grpc_addr": "localhost:7899",
                        "tls_cert_file": "/etc/notary/tls/tls.crt",
                        "tls_key_file": "/etc/notary/tls/tls.key",
                        "client_ca_file": "/etc/notary/tls/ca.crt"
                },
                "logging": {
                        "level": "info"
                },
                "storage": {
                        "backend": "mysql",
                        "default_alias": "notarydemopassword"
                }
        }