apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notary

resources:
- migrate-job.yaml
- deployment.yaml
- service.yaml
- ingressroute.yaml
- serverstransport.yaml

secretGenerator:
  - name: notarysigner
    literals:
    - NOTARY_SIGNER_NOTARYDEMOPASSWORD=demopassword

configMapGenerator:
  - name: scripts
    files:
    - scripts/migrate.sh

  - name: notaryserver
    literals:
      - |
        server-config.json=
        {
                "server": {
                        "http_addr": ":4443",
                        "tls_key_file": "/etc/notary/tls/tls.key",
                        "tls_cert_file": "/etc/notary/tls/tls.crt"
                },
                "trust_service": {
                        "type": "remote",
                        "hostname": "localhost",
                        "port": "7899",
                        "key_algorithm": "ecdsa",
                        "tls_ca_file": "/etc/notary/tls/ca.crt",
                        "tls_client_cert": "/etc/notary/tls/tls.crt",
                        "tls_client_key": "/etc/notary/tls/tls.key"
                },
                "logging": {
                        "level": "info"
                },
                "storage": {
                        "backend": "postgres",
                        "db_url": "postgres://server@notary-postgresql:5432/notaryserver?sslmode=verify-full&sslrootcert=/etc/notary/tls/ca.crt&sslcert=/etc/notary/tls/tls.crt&sslkey=/etc/notary/tls/tls.key"
                }
        }

  - name: notarysigner
    literals:
      - |
        signer-config.json=
        {
                "server": {
                        "grpc_addr": "localhost:7899",
                        "tls_cert_file": "/etc/notary/tls/tls.crt",
                        "tls_key_file": "/etc/notary/tls/tls.key",
                        "client_ca_file": "/etc/notary/tls/ca.crt"
                },
                "logging": {
                        "level": "info"
                },
                "storage": {
                        "backend": "postgres",
                        "db_url": "postgres://signer@notary-postgresql:5432/notarysigner?sslmode=verify-full&sslrootcert=/etc/notary/tls/ca.crt&sslcert=/etc/notary/tls/tls.crt&sslkey=/etc/notary/tls/tls.key",
                        "default_alias": "notarydemopassword"
                }
        }