#cloud-config
ssh_authorized_keys:
  # rio
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICWtWFDuehS1fPkSPO91U6BN8lIw4lmBFc/WlDGIT18F cardno:000612025596
  # mo
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLfMDhB0sPSwEEW82D/6a6Sluzp6UJkzWd9CKUMzQs/auyMeyXTU+tGMI9zQJ6c4hq9eAo1yliCmmgmD+5VNTgRd9+gCPebLLQhdlsD/vU8GOnH8OlSLTgtlg4GQSc/ACT9mtVNExbWoNIHuN2s7tyhmwK2yxzALqcWF9OlAMc7UhxIIpeBflkcbMcDf3InRqNBpnXmJOCl1UUpqr6MJYVN6JW+eF5D3E1w5TInfS8byDZdw+glhQ1Fcst/60+hKLF78igrCbCT0yck3GmitLwJFpF3c3sizbVS11xrs9DHMLWZDwFy6UjJ/v2Hv5F8SqxXnYfIQ4AJsr3m/1zKTeoTt0cnwlJOd1FbqUfE/fPlloaokDd/oOSWt6UBMfmdGFVCCCj1gOROYSGkW7tl4ytRMcHx19NJrDe1J6YJjj3RSgbcV1llLZi/vhezzS9qL0K1GuS37I2+u9AO8ilrTP6nhcsf8n3TixbKNMW47ZD+nforcsQSpRafn+jANjlM/0= melamin@MBP.local
packages:
  - qemu-guest-agent
  - iptables-persistent
runcmd:
  - systemctl enable --now qemu-guest-agent